### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by alvinwan** [CS70/queue#19]
~~view queue for specific location (show only requests for that location)~~ (obsolete)
- [x] queue setting: student welcome message
- [x] allow student to cancel request

**Comment by priyamdas** [comment]
I would suggest a feature that allows students to delete themselves off the queue/delete their request. This would be useful for times when they have to leave office hours before their request is processed.

**Comment by alvinwan** [comment]
good idea thanks! (issue updated with new to-do)
