### ISSUE TITLE
Error on signup

### ISSUE THREAD

**Issue by smilli** [CS70/queue#22]
After confirming that I wanted to join I got this error:

<img width="904" alt="screen shot 2016-02-02 at 8 17 50 am" src="https://cloud.githubusercontent.com/assets/5109188/12755741/8eb7098e-c985-11e5-81b9-94ba524586b1.png">

**Comment by alvinwan** [comment]
For staff.eecs70.org?

**Comment by smilli** [comment]
Yup

**Comment by alvinwan** [comment]
@smilli Sorry about that! It should be fixed now.

**Comment by alvinwan** [comment]
Closing this issue, but feel free to reopen if you still get this error.
