### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by elaine84** [CS70/queue#28]
I was just poking around http://staff.eecs70.org/ and got this... I had clicked on an event (I think one of the Homework Party @ Woz events).  I was not signed in on the site.

**Comment by alvinwan** [comment]
Mm. Wasn't able to replicate, but I will investigate. Thanks!

**Comment by luise** [comment]
I have the same issue for lab Friday 11-1pm, 1/29 (http://cs61b.piipod.com/u/21). I'm not sure if the link works for you, but this is where I get the error: http://cs61b.piipod.com/e/20/.

**Comment by alvinwan** [comment]
Oh, thanks! Yeah, I'm seeing the error too. Will get this wrapped up asap.

**Comment by alvinwan** [comment]
Fixed!

**Comment by luise** [comment]
Awesome. Thanks!

**Comment by elaine84** [comment]
Nice!  :)
