### ISSUE TITLE
ImportError: cannot import name 'PhoneNumberField'

### ISSUE THREAD

**Issue by jordanhart** [CS70/queue#50]
Hi! 
I am trying to run through the README to install this locally.
My computer configuration - Arch linux, mariadb, python3.

After I installed, set up my database, activated by "source env/bin/activate" and ran python3 run.py -db create, I got this error 
"ImportError: cannot import name 'PhoneNumberField'."

Do you know what it might be or have any good tips for approaching/finding the problem?

Thank you so much!

**Comment by alvinwan** [comment]
Thanks to @Sumukh for the suggestion: try installing `wtforms-alchemy==0.16.1`. I listed an outdated version in `requirements.txt`.

**Comment by alvinwan** [comment]
The above should work - `requirements.txt` has been updated accordingly. Feel free to re-open if the problem persists.
